# https://github.com/ryasrdp/2025-LR-S7-AutoTesting-JS/tree/unit-test-jest/.github/workflows

name: Unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test